### ISSUE TITLE
Buster is not able to specify the input path on MacOS 10.13.5  preferences 

### ISSUE THREAD

**Issue by pa3eke** [mcdermj/buster#55] opened 2018-06-14 19:40 UTC
I posted my problem in the user group  of nw-digital radio 
https://nw-digital-radio.groups.io/g/main/topic/22186801#1784
and got a lot of respons of hams who have the same issue after updating Mac OS to 10.13.5
Kind regards and thumbs up for your nice program which is unfortunately not usable anymore'
Rob

**Comment by richark** [comment] 2018-06-14 19:51
Rob,

I'm recommending closing this issue, since it is a duplicate of the issue created yesterday. (https://github.com/mcdermj/buster/issues/54)

I'm sure this is related to a change that Apple made and I know Anna is using standard libraries for the audio input/output, so hopefully this will be a easy fix.

73,
Kenny

**Comment by mcdermj** [comment] 2018-06-14 19:53
Duplicate of #54.  Closing

**Closed by mcdermj** 2018-06-14 19:53 UTC
Labels: duplicate
