### ISSUE TITLE
Sierra updates leaving Buster buggy. . . 

### ISSUE THREAD

**Issue by boomertype** [mcdermj/buster#46] opened 2017-03-21 04:36 UTC
After the switch over to Buster, I'm having issues with a few things.
1.  Announce Reflector Status Changes in the Preferences, no longer getting announcements.  I've rebooted, and also tossed and redownloaded the program.
2.  Play Courtesy Tone at End of Tranmissions - no longer working.
3.  After the last update to Sierra - Version 10.12.3 (16D32) I get frequent disconnects and have to relink,  No announcement, just disconnects in the middle of PTT.

These are a big problem for me as I use Buster to connect and observe a net - The Raspberry Pi DStar Net on REF038C on Monday evenings at 7pm PDT.  I'm the third Wed of the month Net Control and tonight I disconnected more times than I could count, and had to switch to my Icom thru my Raspberry Pi.  I prefer Buster as it has been rock solid and gives me a running log of my check-ins and all those keying up.  Feel free to contact me at my email - jim.fielder@outlook.com.
In addition, as I was having the problem - I rebooted the Mac (new this past summer) and rebooted Buster several times.  I'd switch back to the RPi and the radio.  Several net regulars shared they were having Buster issues also and two said they had abandoned the ThumbDV because of it's problems as of late.  
Hoping you can get this fixed.

Jim Fielder
WA7VFQ

**Comment by mcdermj** [comment] 2017-05-30 00:11
1:  Fixed in 0a0e68c
2:  Cannot reproduce, will continue to look at the issue.
3:  Fixed in ce3c8e8

In the future, one bug report per issue.  That helps track them more easily.

**Comment by boomertype** [comment] 2017-05-30 02:21
Thanks Jeremy, do you know when the update will be available to update at the AppStore?


Jim

WA7VFQ



________________________________

**Comment by mcdermj** [comment] 2017-05-30 03:41
> On May 29, 2017, at 7:21 PM, boomertype <notifications@github.com> wrote:
> 
> Thanks Jeremy, do you know when the update will be available to update at the AppStore?

v1.0.2 is pending review by Apple right now.


> Jim
> 
> WA7VFQ


--
Jeremy McDermond (NH6Z)
Xenotropic Systems
mcdermj@xenotropic.com

**Comment by boomertype** [comment] 2017-05-30 04:55
Thanks again Jeremy!  I love this software.  I do net control for the Raspberry Pi DStar net and the callsign list make it very doable.  Love the Mac platform.  Great software, thanks for you supporting it.


Jim Fielder

WA7VFQ



________________________________

**Closed** 2017-05-31 03:01 UTC
